### ISSUE TITLE
[refinement] Suspect data allocation

### ISSUE THREAD

**Issue by HarrisonShort** [njramage/SilenceTheSnitch#36]
Currently during game setup, GameManager generates the suspect data before passing the information to UI Manager so that it can setup the suspect prefabs on screen.

The generation of suspect data right now is rudimentary. It needs to be refined so that, as per the [storyboard info](https://docs.google.com/document/d/10q50XOLaP9kbUiRT_XSfFPBM2i185VxwfjzLaGzYFoQ/edit?tab=t.0), at least two suspects share two attributes with another suspect.

Additionally, either here or in a future ticket, difficulty needs to be considered.

**Comment by njramage** [comment]
from play testing this is fine
